version: '3.8'

services:

  db:
    image: mysql
    restart: always
    container_name: db-beers
    build:
      context: ./sql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_DATABASE: "beer"

  api:
    container_name: api-beers
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '80:5000'
    depends_on: 
    - db