version: '3.8'

services:

  db:
    image: mysql
    restart: always
    container_name: db-beers
    build: ./sql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_DATABASE: "beer"

  api:
    container_name: api-beers
    build: ./api/Dockerfile
    ports:
      - '5000:80'
    depends_on: db